#!/usr/bin/env expect

eval spawn "panopticon book scrna-wizard"
expect "Location of .loom"
send "./example_data/\n"
expect "Name of .loom"
send "example.loom\n"
expect "Data/counts matrix"
send "./example_data/Example_Sparse_Data.npz\n"
#send "./example_data/Example_Tumor_Data.txt\n"
#expect "header"
#send "n\n"
expect "Cell metadata"
send "./example_data/Example_Tumor_Metadata.txt\n"
expect "corresponding to complexity"
send "y\n"
expect "Which column"
send "nGene\n"
expect "corresponding to patient identity"
send "y\n"
expect "Which column"
send "patient_ID\n"
expect "corresponding to cell type"
send "y\n"
expect "Which column"
send "cell.type\n"
expect "Gene metadata"
send "./example_data/Example_Genes.txt\n"
expect "header"
send "n\n"
expect "complete"
